export type Locale = 'ar' | 'en';

export const BUSINESS_TYPES = [
  'restaurant',
  'cafe',
  'bakery',
  'fast_food',
  'cloud_kitchen',
  'other',
] as const;

export type BusinessType = (typeof BUSINESS_TYPES)[number];

export const copy = {
  ar: {
    brand: 'Engaz',
    byline: 'by ILC Soft',
    theme: {
      toLight: 'الوضع الفاتح',
      toDark: 'الوضع الداكن',
    },
    nav: {
      features: 'المميزات',
      how: 'كيف نشتغل',
      faq: 'أسئلة',
      start: 'ابدأ الآن',
      login: 'تسجيل الدخول',
    },
    hero: {
      kicker: 'QR Menu',
      title: 'منيو رقمي لمطعمك — من الكيو آر للطلب في ثوانٍ',
      subtitle:
        'ضيفك يمسح، يشوف المنيو بالعربي والإنجليزي، ويطلب واتساب. أنت تتابع المسحات والأطباق الأكثر طلبًا.',
      cta: 'ابدأ الآن',
      secondary: 'شوف المميزات',
      chips: ['بدون بوابة دفع', 'عربي / English', 'واتساب للطلب'],
    },
    trust: {
      title: 'شغّال على مواقع حقيقية',
      items: ['قائمة QR ثنائية اللغة', 'تحليلات المسح', 'استيراد بالذكاء الاصطناعي'],
    },
    beforeAfter: {
      title: 'من ورق يتبهدل… لكيو آر يتحدّث معك',
      before: 'منيو مطبوع',
      after: 'منيو QR',
      beforeItems: ['تعديل السعر يعني طبعة جديدة', 'ضيفك يمسك ورقة بين الأكل', 'ما تعرف إيه اللي بيتطلب'],
      afterItems: ['حدّث السعر من لوحة التحكم', 'المسح يفتح المنيو على الموبايل', 'تعرف أطباقك وساعات الذروة'],
    },
    featuresTitle: 'اللي فعلًا موجود في المنتج',
    features: [
      { title: 'قوائم QR', body: 'كيو آر على الطاولة يفتح منيو بصور وأسعار وتوافر لحظي.' },
      { title: 'عربي وإنجليزي', body: 'واجهة RTL جاهزة، والتبديل بين اللغات من غير ما تكسّر التصميم.' },
      { title: 'تصنيفات وصور', body: 'أقسام، صور، أسعار، وإخفاء الأصناف غير المتاحة.' },
      { title: 'طلب واتساب', body: 'السلة تتحول لرسالة واتساب. مفيش دفع إلكتروني جوه المنصة.' },
      { title: 'تحليلات', body: 'مسحات QR، الأطباق الأكثر مشاهدة، وساعات الذروة.' },
      { title: 'استيراد بالذكاء الاصطناعي', body: 'ارفع PDF أو صور المنيو، والنظام يقترح الأصناف للمراجعة.' },
      { title: 'صالة / سفري / توصيل', body: 'طرق استلام تناسب المطعم — مش سوبرماركت بس.' },
      { title: '٥ قوالب QR', body: 'أشكال جاهزة للطباعة على الطاولات والاستاندات.' },
    ],
    howTitle: 'أربع خطوات لحد ما المنيو يبقى لايف',
    how: [
      { n: '١', title: 'قدّم طلبك', body: 'اسم النشاط، بياناتك، واللوجو أو المنيو لو جاهزين.' },
      { n: '٢', title: 'نراجع الطلب', body: 'فريق إنجز يراجع البيانات ويحدد قالب الموقع.' },
      { n: '٣', title: 'نجهّز المنيو', body: 'نبني موقع المطعم على رابط خاص بيك.' },
      { n: '٤', title: 'QR على الطاولة', body: 'تطبع الكيو آر، والضيف يمسح ويطلب.' },
    ],
    demosTitle: 'جرّب مواقع شغالة',
    demosVisit: 'افتح الموقع',
    demos: [
      {
        name: 'Harameen',
        url: 'https://harameen.engazqr.com/',
        preview: '/demos/harameen-icon.png',
      },
      {
        name: 'Warda Shamya',
        url: 'https://wardashamya.engazqr.com/',
        preview: '/demos/warda-icon.png',
      },
      {
        name: 'Aklet Gambary',
        url: 'https://akletgambary.engazqr.com/',
        preview: '/demos/aklet-icon.png',
      },
    ],
    qrTitle: 'الضيف يمسح — المنيو يفتح',
    qrBody: 'الكود على الطاولة، المنيو على الموبايل، والطلب على واتساب. من غير تطبيق يتنزّل.',
    faqTitle: 'أسئلة متكررة',
    faq: [
      {
        q: 'هل أقدر أدفع أونلاين من المنيو؟',
        a: 'لا. الطلب بيتم عبر واتساب. مفيش بوابة دفع جوه Engaz.',
      },
      {
        q: 'هل أسجّل الدخول من هنا بعد التسجيل؟',
        a: 'بعد ما نجهّز موقعك، تسجّل الدخول على رابط مطعمك. مش من لوحة Engaz Admin.',
      },
      {
        q: 'إيه اللي بيحصل بعد ما تقدّم الطلب؟',
        a: 'طلبك يدخل قائمة المراجعة. هنجهّز المنيو ونتواصل معاك. مفيش لوحة تحكم وهمية بعد الفورم.',
      },
      {
        q: 'الموقع عربي وإنجليزي؟',
        a: 'نعم. المنيو يدعم العربي والإنجليزي وواجهة RTL.',
      },
      {
        q: 'أقدر أرفع منيو PDF؟',
        a: 'نعم. تقدر ترفعه مع الطلب، أو تبعت الملف لاحقًا. الاستيراد بالذكاء الاصطناعي جزء من المنتج.',
      },
    ],
    cta: {
      title: 'جهّز منيو QR لمطعمك',
      body: 'املأ الطلب، وهنستلم بياناتك ونبدأ التجهيز.',
      button: 'ابدأ الآن',
    },
    footer: {
      legal: 'سياسة الخصوصية',
      terms: 'شروط الاستخدام',
      login: 'دخول الفريق',
      note: 'Engaz منتج من ILC Soft. لا ننشر رقم هاتف أو تسعير من هذه الصفحة.',
    },
    login: {
      title: 'تسجيل الدخول',
      ownerTitle: 'أصحاب المطاعم',
      ownerBody:
        'بعد ما نجهّز موقعك، سجّل الدخول على الرابط الخاص بمطعمك — مش من هنا، ومش من لوحة Engaz Admin.',
      staffTitle: 'فريق Engaz',
      staffBody: 'لوحة التحكم للسوبر أدمن فقط.',
      staffCta: 'دخول Engaz Admin',
      back: 'العودة للرئيسية',
    },
    register: {
      title: 'ابدأ الآن',
      subtitle: 'طلب انضمام. مش لوحة تحكم، ومش تفعيل تلقائي.',
      steps: ['حسابك', 'نشاطك', 'المنيو', 'تم الاستلام'],
      ownerName: 'الاسم',
      email: 'البريد الإلكتروني',
      phone: 'رقم الموبايل',
      password: 'كلمة مرور لوحة مطعمك لاحقًا',
      passwordHint: 'هنحفظها مشفّرة لاستخدامها على موقع مطعمك بعد التجهيز. مش لدخول Engaz Admin.',
      businessName: 'اسم النشاط',
      businessType: 'نوع النشاط',
      address: 'العنوان',
      city: 'المدينة',
      logo: 'اللوجو (اختياري)',
      menu: 'المنيو PDF أو صورة (اختياري)',
      skipFiles: 'تخطي الملفات',
      next: 'التالي',
      back: 'رجوع',
      submit: 'إرسال الطلب',
      successTitle: 'تم استلام طلبك',
      successBody: 'أهلاً بك — طلبك وصل، هنتواصل ونجهّز المنيو. تقدر تبعت الملف لاحقًا لو ما اترفخش دلوقتي.',
      successUploadWarn: 'تم حفظ الطلب، لكن رفع الملف فشل. تقدر تبعت اللوجو أو المنيو لاحقًا.',
      home: 'العودة للرئيسية',
      types: {
        restaurant: 'مطعم',
        cafe: 'كافيه',
        bakery: 'مخبز',
        fast_food: 'وجبات سريعة',
        cloud_kitchen: 'مطبخ سحابي',
        other: 'أخرى',
      },
      errors: {
        required: 'من فضلك أكمل الحقول المطلوبة.',
        email: 'البريد الإلكتروني غير صالح.',
        duplicate: 'البريد ده مسجّل قبل كده. لو الطلب عندنا، هنراجعه.',
        network: 'حصل خطأ في الشبكة. جرّب تاني بعد شوية.',
        upload: 'الملف أكبر من المسموح أو نوعه غير مدعوم.',
        generic: 'ما قدرناش نستلم الطلب دلوقتي. جرّب تاني.',
        password: 'كلمة المرور لازم ٨ حروف على الأقل.',
      },
    },
    legalUpdated: 'آخر تحديث: أغسطس 2026',
  },
  en: {
    brand: 'Engaz',
    byline: 'by ILC Soft',
    theme: {
      toLight: 'Light mode',
      toDark: 'Dark mode',
    },
    nav: {
      features: 'Features',
      how: 'How it works',
      faq: 'FAQ',
      start: 'Start now',
      login: 'Log in',
    },
    hero: {
      kicker: 'QR Menu',
      title: 'A digital menu for your restaurant — scan to order in seconds',
      subtitle:
        'Guests scan, browse Arabic and English, and order on WhatsApp. You see scans, top dishes, and peak hours.',
      cta: 'Start now',
      secondary: 'See features',
      chips: ['No payment gateway', 'Arabic / English', 'WhatsApp ordering'],
    },
    trust: {
      title: 'Already live on real sites',
      items: ['Bilingual QR menus', 'Scan analytics', 'AI menu import'],
    },
    beforeAfter: {
      title: 'From a paper menu that goes stale to a QR that stays current',
      before: 'Printed menu',
      after: 'QR menu',
      beforeItems: ['A price change means a reprint', 'Guests handle a shared card', 'You cannot see what gets attention'],
      afterItems: ['Update prices from the dashboard', 'Scan opens the menu on a phone', 'See dishes and peak hours'],
    },
    featuresTitle: 'What the product actually does',
    features: [
      { title: 'QR menus', body: 'A table QR opens a live menu with photos, prices, and availability.' },
      { title: 'Arabic and English', body: 'RTL-ready UI with a language switch that keeps the layout intact.' },
      { title: 'Categories and photos', body: 'Sections, images, prices, and hide items that are out.' },
      { title: 'WhatsApp ordering', body: 'The cart becomes a WhatsApp message. No in-app payments.' },
      { title: 'Analytics', body: 'QR scans, most-viewed dishes, and peak hours.' },
      { title: 'AI import', body: 'Upload a PDF or photos; the system drafts items for review.' },
      { title: 'Dine-in / takeaway / delivery', body: 'Fulfillment modes that fit a restaurant — not only retail.' },
      { title: '5 QR templates', body: 'Print-ready styles for tables and stands.' },
    ],
    howTitle: 'Four steps until the menu is live',
    how: [
      { n: '1', title: 'Send your request', body: 'Business name, your details, and a logo or menu if you have them.' },
      { n: '2', title: 'We review', body: 'The Engaz team reviews the application and chooses a site template.' },
      { n: '3', title: 'We set up the menu', body: 'Your restaurant gets its own live URL.' },
      { n: '4', title: 'QR on the table', body: 'Print the code. Guests scan and order.' },
    ],
    demosTitle: 'Live demos',
    demosVisit: 'Visit site',
    demos: [
      {
        name: 'Harameen',
        url: 'https://harameen.engazqr.com/',
        preview: '/demos/harameen-icon.png',
      },
      {
        name: 'Warda Shamya',
        url: 'https://wardashamya.engazqr.com/',
        preview: '/demos/warda-icon.png',
      },
      {
        name: 'Aklet Gambary',
        url: 'https://akletgambary.engazqr.com/',
        preview: '/demos/aklet-icon.png',
      },
    ],
    qrTitle: 'Guests scan — the menu opens',
    qrBody: 'Code on the table, menu on the phone, order on WhatsApp. No app to install.',
    faqTitle: 'FAQ',
    faq: [
      {
        q: 'Can guests pay in the menu?',
        a: 'No. Orders go through WhatsApp. Engaz does not include a payment gateway.',
      },
      {
        q: 'Do I log in here after registering?',
        a: 'After we provision your site, you sign in on your restaurant URL — not here, and not on Engaz Admin.',
      },
      {
        q: 'What happens after I submit a request?',
        a: 'Your request joins a review queue. We prepare the menu and contact you. There is no fake dashboard after the form.',
      },
      {
        q: 'Is the menu bilingual?',
        a: 'Yes. Arabic and English, with RTL support.',
      },
      {
        q: 'Can I upload a PDF menu?',
        a: 'Yes, with the request or later. AI import is part of the product.',
      },
    ],
    cta: {
      title: 'Get a QR menu for your restaurant',
      body: 'Submit the request. We receive your details and start setup.',
      button: 'Start now',
    },
    footer: {
      legal: 'Privacy',
      terms: 'Terms',
      login: 'Staff login',
      note: 'Engaz is a product of ILC Soft. This page does not list a phone number or prices.',
    },
    login: {
      title: 'Log in',
      ownerTitle: 'Restaurant owners',
      ownerBody:
        'After we provision your site, sign in on your restaurant URL — not here, and not on the Engaz Admin console.',
      staffTitle: 'Engaz staff',
      staffBody: 'The control plane is for super-admins only.',
      staffCta: 'Engaz Admin login',
      back: 'Back to home',
    },
    register: {
      title: 'Start now',
      subtitle: 'This is an application — not a dashboard and not auto-provisioning.',
      steps: ['Your account', 'Your business', 'Menu files', 'Received'],
      ownerName: 'Full name',
      email: 'Email',
      phone: 'Phone',
      password: 'Password for your future restaurant admin',
      passwordHint:
        'Stored encrypted for your customer site later. It does not sign you into Engaz Admin.',
      businessName: 'Business name',
      businessType: 'Business type',
      address: 'Address',
      city: 'City',
      logo: 'Logo (optional)',
      menu: 'Menu PDF or photo (optional)',
      skipFiles: 'Skip files',
      next: 'Continue',
      back: 'Back',
      submit: 'Submit request',
      successTitle: 'تم استلام طلبك',
      successBody:
        'Welcome — we received your request and will prepare the menu. You can send files later if you skipped them.',
      successUploadWarn: 'The request was saved, but the file upload failed. You can send the logo or menu later.',
      home: 'Back to home',
      types: {
        restaurant: 'Restaurant',
        cafe: 'Café',
        bakery: 'Bakery',
        fast_food: 'Fast food',
        cloud_kitchen: 'Cloud kitchen',
        other: 'Other',
      },
      errors: {
        required: 'Please complete the required fields.',
        email: 'That email does not look valid.',
        duplicate: 'This email is already in the queue. We will review the existing request.',
        network: 'Network error. Please try again shortly.',
        upload: 'The file is too large or the type is not supported.',
        generic: 'We could not receive the request right now. Please try again.',
        password: 'Password must be at least 8 characters.',
      },
    },
    legalUpdated: 'Last updated: August 2026',
  },
} as const;
